# Main background, empty for terminal default, need to be empty if you want transparent background
theme[main_bg]="#0B1113"

# Main text color
theme[main_fg]="#D8E3E0"

# Title color for boxes
theme[title]="#D8E3E0"

# Highlight color for keyboard shortcuts
theme[hi_fg]="#33B8A8"

# Background color of selected item in processes box
theme[selected_bg]="#304144"

# Foreground color of selected item in processes box
theme[selected_fg]="#F2F8F6"

# Color of inactive/disabled text
theme[inactive_fg]="#718688"

# Color of text appearing on top of graphs, i.e uptime and current network graph scaling
theme[graph_text]="#D9C76B"

# Background color of the percentage meters
theme[meter_bg]="#223033"

# Misc colors for processes box including mini cpu graphs, details memory graph and details status text
theme[proc_misc]="#A4B4B2"

# CPU, Memory, Network, Proc box outline colors
theme[cpu_box]="#4DBA7A"
theme[mem_box]="#5CCBBB"
theme[net_box]="#5E9BFF"
theme[proc_box]="#78ACFF"

# Box divider line and small boxes line color
theme[div_line]="#223033"

# Temperature graph color (Green -> Yellow -> Red)
theme[temp_start]="#4DBA7A"
theme[temp_mid]="#D9C76B"
theme[temp_end]="#E16F73"

# CPU graph colors (Teal -> Lavender)
theme[cpu_start]="#4DBA7A"
theme[cpu_mid]="#59D6C5"
theme[cpu_end]="#D8E3E0"

# Mem/Disk free meter (Mauve -> Lavender -> Blue)
theme[free_start]="#5E9BFF"
theme[free_mid]="#78ACFF"
theme[free_end]="#D8E3E0"

# Mem/Disk cached meter (Sapphire -> Lavender)
theme[cached_start]="#223033"
theme[cached_mid]="#304144"
theme[cached_end]="#4A5F62"

# Mem/Disk available meter (Peach -> Red)
theme[available_start]="#A4B4B2"
theme[available_mid]="#D9C76B"
theme[available_end]="#E16F73"

# Mem/Disk used meter (Green -> Sky)
theme[used_start]="#4DBA7A"
theme[used_mid]="#67CF94"
theme[used_end]="#5CCBBB"

# Download graph colors (Peach -> Red)
theme[download_start]="#5E9BFF"
theme[download_mid]="#78ACFF"
theme[download_end]="#A4B4B2"

# Upload graph colors (Green -> Sky)
theme[upload_start]="#33B8A8"
theme[upload_mid]="#59D6C5"
theme[upload_end]="#5CCBBB"

# Process box color gradient for threads, mem and cpu usage (Sapphire -> Mauve)
theme[process_start]="#5E9BFF"
theme[process_mid]="#A4B4B2"
theme[process_end]="#33B8A8"
