accent = "#33b8a8"
cursor = "#d8e3e0"
foreground = "#d8e3e0"
background = "#0b1113"
selection_foreground = "#f2f8f6"
selection_background = "#365156"

color0 = "#182326"
color1 = "#e16f73"
color2 = "#4dba7a"
color3 = "#d9c76b"
color4 = "#5e9bff"
color5 = "#59d6c5"
color6 = "#33b8a8"
color7 = "#c0cecb"
color8 = "#4a5f62"
color9 = "#f08787"
color10 = "#67cf94"
color11 = "#efd45e"
color12 = "#78acff"
color13 = "#71e4d8"
color14 = "#5ccbbb"
color15 = "#f2f8f6"
