mode = "dark"

accent = "#33b8a8"
selection = "#365156"
muted = "#718688"

background = "#0b1113"
dark_background = "#0e1518"
darker_background = "#020405"
lighter_background = "#182326"

foreground = "#d8e3e0"
dark_foreground = "#4a5f62"
light_foreground = "#c0cecb"
bright_foreground = "#f2f8f6"

selection_foreground = "#f2f8f6"

red = "#e16f73"
yellow = "#d9c76b"
orange = "#e16f73"
green = "#4dba7a"
cyan = "#33b8a8"
blue = "#5e9bff"
magenta = "#59d6c5"

bright_red = "#f08787"
bright_yellow = "#efd45e"
bright_green = "#67cf94"
bright_cyan = "#5ccbbb"
bright_blue = "#78acff"
bright_magenta = "#71e4d8"
